version: "3.4"

services:
  api:
    image: registry.gitlab.com/pronostieken/api
    networks:
      - reverse-proxy_default
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=n05YfG8sGkkUQxUyhaZa
      - MSSQL_PID=Express
    volumes:
      - /root/pronostieken/mssql:/var/opt/mssql

networks:
  reverse-proxy_default:
    external: true
